package com.maxwell.classcreator.view;

import com.maxwell.classcreator.control.JsonController;
import com.maxwell.classcreator.model.Json;
import javax.swing.JOptionPane;

/**
 *
 * @author Maxwell Knoxx - 06/2019
 */
public class View extends javax.swing.JFrame {

    JsonController jsonController = new JsonController();

    /**
     * Creates new form view
     */
    public View() {
        initComponents();
    }

    public String getPath() {
        return jTextFieldPath.getText();
    }

    public String getJsonText() {
        return jTextAreaJson.getText();
    }

    public Boolean isEntitySelected() {
        return jCheckBoxEntity.isSelected();
    }

    public Boolean isModelSelected() {
        return jCheckBoxModel.isSelected();
    }

    public Boolean isServiceImplSelected() {
        return jCheckBoxServiceImpl.isSelected();
    }

    public Boolean isRepositorySelected() {
        return jCheckBoxRepository.isSelected();
    }

    public Boolean validatePath() {
        if (!jTextFieldPath.getText().isEmpty()) {
            return true;
        }
        showErrorMessage("Please, select a path!");
        return false;
    }

    private boolean validateJsonField() {
        if (!jTextAreaJson.getText().isEmpty()) {
            return true;
        }
        showErrorMessage("Please, fill the Json field");
        return false;
    }

    //apply regex
    private Boolean validateJsonStructure() {
        if (jTextAreaJson.getText().contains("{") && jTextAreaJson.getText().contains("}")) {
            return true;
        }
        showErrorMessage("The Json structure is wrong!");
        return false;
    }

    private void createFiles() {
        Json json = new Json();

        json.setPath(getPath());
        json.setText(getJsonText());
        json.setCreateEntity(isEntitySelected());
        json.setCreateModel(isModelSelected());
        json.setCreateServiceImpl(isServiceImplSelected());
        json.setCreateRepository(isRepositorySelected());

        jsonController.generateFiles(json);
        showMessage("the files were created!");
    }

    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPath = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jLabelJson = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaJson = new javax.swing.JTextArea();
        jCheckBoxEntity = new javax.swing.JCheckBox();
        jCheckBoxModel = new javax.swing.JCheckBox();
        jCheckBoxServiceImpl = new javax.swing.JCheckBox();
        jCheckBoxRepository = new javax.swing.JCheckBox();
        jButtonCreate = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPath.setText("Path: ");
        getContentPane().add(jLabelPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jTextFieldPath.setText("/Users/Macbook/Documents");
        getContentPane().add(jTextFieldPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, -1));

        jButtonBrowse.setText("Browse");
        getContentPane().add(jButtonBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabelJson.setText("JSON:");
        getContentPane().add(jLabelJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextAreaJson.setColumns(20);
        jTextAreaJson.setRows(5);
        jScrollPane1.setViewportView(jTextAreaJson);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 160));

        jCheckBoxEntity.setText("Entity");
        getContentPane().add(jCheckBoxEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jCheckBoxModel.setText("Model");
        getContentPane().add(jCheckBoxModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jCheckBoxServiceImpl.setText("Service/Impl");
        getContentPane().add(jCheckBoxServiceImpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jCheckBoxRepository.setText("Repository");
        getContentPane().add(jCheckBoxRepository, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jButtonCreate.setText("Create");
        jButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabelName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelName.setText("CLASS CREATOR 2000 PLUS");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateActionPerformed
        if (validatePath()) {
            if (validateJsonField()) {
                if (validateJsonStructure()) {
                    createFiles();
                }
            }
        }
    }//GEN-LAST:event_jButtonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View view = new View();
                view.setResizable(false);
                view.setLocationRelativeTo(null);
                view.setTitle("Class creator");
                view.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JCheckBox jCheckBoxEntity;
    private javax.swing.JCheckBox jCheckBoxModel;
    private javax.swing.JCheckBox jCheckBoxRepository;
    private javax.swing.JCheckBox jCheckBoxServiceImpl;
    private javax.swing.JLabel jLabelJson;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPath;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaJson;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables

}
