/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.maxwell.classcreator.view;

/**
 *
 * @author Macbook
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPath = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jLabelJson = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBoxEntity = new javax.swing.JCheckBox();
        jCheckBoxModel = new javax.swing.JCheckBox();
        jCheckBoxServiceImpl = new javax.swing.JCheckBox();
        jCheckBoxRepository = new javax.swing.JCheckBox();
        jButtonCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPath.setText("Path: ");
        getContentPane().add(jLabelPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(jTextFieldPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, -1));

        jButtonBrowse.setText("Browse");
        getContentPane().add(jButtonBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabelJson.setText("JSON:");
        getContentPane().add(jLabelJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 160));

        jCheckBoxEntity.setText("Entity");
        jCheckBoxEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEntityActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxEntity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jCheckBoxModel.setText("Model");
        getContentPane().add(jCheckBoxModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jCheckBoxServiceImpl.setText("Service/Impl");
        getContentPane().add(jCheckBoxServiceImpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jCheckBoxRepository.setText("Repository");
        getContentPane().add(jCheckBoxRepository, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jButtonCreate.setText("Create");
        getContentPane().add(jButtonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("CLASS CREATOR 2000 PLUS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEntityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEntityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View view = new View();
                view.setResizable(false);
                view.setLocationRelativeTo(null);
                view.setTitle("Class creator");
                view.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JCheckBox jCheckBoxEntity;
    private javax.swing.JCheckBox jCheckBoxModel;
    private javax.swing.JCheckBox jCheckBoxRepository;
    private javax.swing.JCheckBox jCheckBoxServiceImpl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelJson;
    private javax.swing.JLabel jLabelPath;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
